name: Synch BitBucket via HTTPS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]

jobs:
   
  syncbb:
    name: Synch from Github to Bitbucket https
    runs-on: ubuntu-latest
    steps:
      - name: pull the github repo
        uses: actions/checkout@v2
      - name: sync with bitbucket
        run: |
          cd $GITHUB_WORKSPACE
          # update the whole repo including tags/branches but prune out deleted items
          git fetch --prune --unshallow 
          # make the bb repo a remote called sync
          git remote add sync ${{ secrets.ASKDATA_GIT_CONNECTION_URL }}/askdata-docs
          # force push the sync remote with all changes.
          git push --force --set-upstream -v --all sync
